version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    container_name: 4ksports-server
    ports:
      - "4700:4700"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - 4ksports-network

networks:
  4ksports-network:
    driver: bridge
